# golangci-lint configuration for gopenapi project
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple  
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - goconst
    - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 