openapi: 3.0.0
info:
  title: Simple Test API
  version: 1.0.0
paths:
  /health:
    get:
      operationId: health_check
      summary: Health check endpoint
      responses:
        '200':
          description: OK
  /ping:
    get:
      operationId: ping
      summary: Ping endpoint
      responses:
        '200':
          description: Pong 