// writer.go - File output operations
package output

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Writer handles writing generated files to disk
type Writer struct {
	RootDir string
}

// OutputFile represents a file to be written
type OutputFile struct {
	Path    string
	Content string
}

// NewWriter creates a new file writer
func NewWriter(rootDir string) *Writer {
	return &Writer{
		RootDir: rootDir,
	}
}

// WriteFiles writes all generated files to disk
func (w *Writer) WriteFiles(files []OutputFile) error {
	for _, file := range files {
		if err := w.WriteFile(file); err != nil {
			return err
		}
	}
	return nil
}

// WriteFile writes a single file to disk
func (w *Writer) WriteFile(file OutputFile) error {
	// Construct the full path
	fullPath := filepath.Join(w.RootDir, file.Path)

	// Create directory if needed
	dir := filepath.Dir(fullPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("error creating directory %s: %w", dir, err)
	}

	// Check if file already exists
	if _, err := os.Stat(fullPath); err == nil {
		// File exists, check if it's generated
		content, err := os.ReadFile(fullPath)
		if err != nil {
			return fmt.Errorf("error reading existing file %s: %w", fullPath, err)
		}

		// Check if the file is generated by looking for the "DO NOT EDIT" marker
		if !strings.Contains(string(content), "DO NOT EDIT") {
			// This file was manually edited, we should not overwrite it
			fmt.Printf("Skipping %s (manually edited)\n", file.Path)
			return nil
		}
	}

	// Write the file
	if err := os.WriteFile(fullPath, []byte(file.Content), 0644); err != nil {
		return fmt.Errorf("error writing file %s: %w", fullPath, err)
	}

	// Format Go code with gofmt if it's a Go file
	if strings.HasSuffix(fullPath, ".go") {
		cmd := exec.Command("gofmt", "-w", fullPath)
		if err := cmd.Run(); err != nil {
			fmt.Printf("Warning: gofmt failed for %s: %v\n", fullPath, err)
			// Continue even if formatting fails
		}
	}

	fmt.Printf("Generated %s\n", file.Path)
	return nil
}
